local smed = LibStub("LibSharedMedia-3.0")
smed:Register("statusbar", "Flat Smooth", "Interface\\AddOns\\MoossaMedia\\bar\\flatsmooth.tga")
smed:Register("statusbar", "Curved Bar", "Interface\\AddOns\\MoossaMedia\\bar\\curvedbar.tga")
smed:Register("statusbar", "Steel", "Interface\\AddOns\\MoossaMedia\\bar\\Steel.tga")
smed:Register("font", "Franklin Gothic Medium", "Interface\\AddOns\\MoossaMedia\\font\\font1.ttf")
smed:Register("border", "Square Outline", "Interface\\AddOns\\MoossaMedia\\border\\squareline.tga")
